import { Injectable } from '@angular/core';
export interface NervesModel{
  category: string;   
  id: string;
  name: string;
  Enname: string;
  faname: string;
  meridian:string;
  Fameridian:string;
  description: string;
  location: string;
  pressureAngle: string;
  pressureAmount: string;
  repetitions: string;
  time: string;
  extra: string;
  imageUrl: string;
  desc: string;
  descrip: string;
  descExtra: string;
  supplementary: string;
}
@Injectable({
  providedIn: 'root'
})
export class NervesService {
  private nerves:NervesModel[]=[
    {
      category: "nerves",
      Enname:"Hapgok, Hegu",
      faname:"هیگو",
      meridian:"Large Intestine Meridian (LI)",
      Fameridian:"مریدین روده بزرگ",
      id:"LI4",
      name:"LI4 Hegu هیگو",
      description:"روی دست",
      location:"محل نقطه: بین انگشت شصت و اشاره",
      pressureAngle:"زاویه فشار بصورت عمود",
      pressureAmount:"میزان فشار بین 7 تا 10",
      repetitions:"بین یک تا سه بار",
      time: "زمان بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یانگ",
      imageUrl:"assets/images/hegu.png",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Sinmun, Shenmen",
      faname:"شین مين",
      meridian:"Heart Meridian (HT)",
      Fameridian:"مریدین قلب",
      id:"HT7",
      name:"HT7 Shenmen شین مين",
      description:"روی دست",
      location:"محل نقطه: پایین انگشت کوچیکه بالاتر از مچ دست",
      pressureAngle:"زاویه فشار: فشار بصورت عمود",
      pressureAmount:"میزان فشار: بین 6 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Naegwan, Neiguan",
      faname:"نايگون",
      meridian:"Pericardium Meridian (PC)",
      Fameridian:"مریدین پریکارد (تامیانه قلب - یک لایه نازک و کیسه‌مانند است که قلب را در بر می‌گیرد)",
      id:"PC6",
      name:"PC6 Neiguan نايگون",
      description:"روی دست",
      location:"محل نقطه: روی دست دو سون بالاتر از مچ ",
      pressureAngle:"زاویه فشار: 45 رو به بالا",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یین",
      imageUrl:"",
      desc: "تهوع، اضطراب، مشکلات گوارشی، آرامش‌بخش بسیار قوی",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Gokji, Quchi",
      faname:"کوچی",
      meridian:"Large Intestine Meridian (LI)",
      Fameridian:"مریدین روده بزرگ",
      id:"LI11",
      name:"LI11 Quchi کوچی ",
      description:"روی دست",
      location:"محل نقطه: خط آرنج دست نیم سون پایینتر ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 2 به بالا",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یانگ",
      imageUrl:"یانگ",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Yintang",
      faname:"چشم سوم",
      meridian:"Third Eye Chakra Ajna",
      Fameridian:"چاکرای چشم سوم / پیشانی",
      id:"Ex1",
      name:"Ex1 Yintang چشم سوم اکسترا پوینت",
      description:"چاکراه چشم سوم",
      location:"محل نقطه: بین ابرو در پیشونی",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 5",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"شهود، درک، بصیرت",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Chanjuk, Zanzhu",
      faname:"ژان ژو",
      meridian:"Bladder Meridian (BL)",
      Fameridian:"مریدین مثانه",
      id:"BL2",
      name:"BL2  Zanzhu ژان ژو",
      description:"روی سر",
      location:"محل نقطه: گودی اول ابروها ",
      pressureAngle:"زاویه فشار: به سمت شقیقه ها",
      pressureAmount:"میزان فشار: بین 3 تا 5",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Duyu, Touwei",
      faname:"",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST8",
      name:"ST8 Touwei",
      description:"روی سر",
      location:"محل نقطه: گوشه ها سر رستنگاه موی سر",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 4 تا 7",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Sangseong, Shangxing",
      faname:"",
      meridian:"Governor Vessel (GV / DU)",
      Fameridian:"مریدین حاکم یا دو",
      id:"GV23",
      name:"GV23 Shangxing",
      description:"روی سر",
      location:"محل نقطه: یک وجب از نوک دماغ تا فرق سر ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 7 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر پشتی بدن، مرتبط با یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Baekhoe, Baihui",
      faname:"بای های",
      meridian:"Governor Vessel (GV / DU)",
      Fameridian:"مریدین حاکم یا دو",
      id:"GV20",
      name:"GV20 Baihui بای های",
      description:"روی سر",
      location:"محل نقطه: عمود از گوش برو بالا تا فرق سر ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 7 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر پشتی بدن، مرتبط با یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Hujeong, Houding",
      faname:"های دینگ",
      meridian:"Governor Vessel (GV / DU)",
      Fameridian:"مریدین حاکم یا دو",
      id:"GV19",
      name:"GV19 Houding های دینگ",
      description:"روی سر",
      location:"محل نقطه: یک و نیم سون پایین تر از بای های",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 7 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر پشتی بدن، مرتبط با یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Pungji, Fengchi",
      faname:"",
      meridian:"Gall Bladder Meridian (GB)",
      Fameridian:"مریدین کیسه صفرا",
      id:"GB20",
      name:"GB20 Fengchi",
      description:"روی سر",
      location:"محل نقطه: پشت گودی سر پایین لاله گوش ",
      pressureAngle:"زاویه فشار: زاویه به سمت بالای سر 45 درجه",
      pressureAmount:"میزان فشار: بین 7 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Gyeonjeong, Jianjing",
      faname:"",
      meridian:"Gall Bladder Meridian (GB)",
      Fameridian:"مریدین کیسه صفرا",
      id:"GB21",
      name:"GB21 Jianjing",
      description:"روی شونه",
      location:"محل نقطه: روی شونه گودی بعد استخوان نصف مهره گردن تا سر شونه ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار:  10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Seon-gi, Xuanji",
      faname:"",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV21",
      name:"CV21 Xuanji",
      description:"روی سینه",
      location:"محل نقطه: سر جناق سینه مماس بر استخوان رو به گودی ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Subu, Shufu",
      faname:"شیفو",
      meridian:"Kidney Meridian (KI)",
      Fameridian:"مریدین کلیه",
      id:"KI27",
      name:"KI27 Shufu شیفو",
      description:"روی سینه",
      location:"محل نقطه: بین استخوان تلقوه و دنده دو سون از Cv21 ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Danjung, Tanzhong",
      faname:"تان ژونگ",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV17",
      name:"CV17 Tanzhong تان ژونگ",
      description:"وسط سینه",
      location:"محل نقطه: بین سر سینه ها گودی وسط سینه ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 2 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Joksamni, Zusanli",
      faname:"ژوسان لی",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST36",
      name:"ST36 Zusanli ژوسان لی",
      description:"روی پا زیر زانو",
      location:"محل نقطه: زیر کشک زانو سمت بیرون زیر استخون گرده",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 6 تا 8",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Seunggeun, Chengjin",
      faname:"",
      meridian:"Bladder Meridian (BL)",
      Fameridian:"مریدین مثانه",
      id:"BL56",
      name:"BL56 Chengjin",
      description:"",
      location:"محل نقطه: 4 عرض انگشت پشت زیر زانو بین ماهیچه دوقلو قله ماهیچه پشت پا ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 6 تا 8",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Sameumgyo, Sanyinjiao",
      faname:"سانین جیو",
      meridian:"Spleen Meridian (SP)",
      Fameridian:"مریدین طحال",
      id:"SP6",
      name:"SP6 Sanyinjiao سانین جیو",
      description:"",
      location:"محل نقطه: داخل پا از مچ پا 4 عرض انگشت بالاتر از پشت استخوان فشار بیارید",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 7 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Sinmaek, Shenmai",
      faname:"شین مای",
      meridian:"Bladder Meridian (BL)",
      Fameridian:"مریدین مثانه",
      id:"BL62",
      name:"BL62 Shenmai شین مای",
      description:"",
      location:"محل نقطه: بیرون پا زیر قوزک  یکم به سمت جلو پا ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 5 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "nerves",
      Enname:"Naejeong, Neiting",
      faname:"نایتینگ",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST44",
      name:"ST44 Neiting نایتینگ",
      description:"",
      location:"محل نقطه: بین انشگت دوم و سوم پا",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 6 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "",
      Enname:"",
      faname:"",
      meridian:"",
      Fameridian:"",
      id:"",
      name:"",
      description:"",
      location:"محل نقطه: ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 7 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "",
      Enname:"",
      faname:"",
      meridian:"",
      Fameridian:"",
      id:"",
      name:"",
      description:"",
      location:"محل نقطه: ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 7 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "",
      Enname:"",
      faname:"",
      meridian:"",
      Fameridian:"",
      id:"",
      name:"",
      description:"",
      location:"محل نقطه: ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 7 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "",
      Enname:"",
      faname:"",
      meridian:"",
      Fameridian:"",
      id:"",
      name:"",
      description:"",
      location:"محل نقطه: ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 7 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "یین (Yin)",
      Enname:"",
      faname:"",
      meridian:"",
      Fameridian:"",
      id:"",
      name:"",
      description:`
مونث  🧘‍♂️
تاریکی 🌑	
زمین 🌍	
سرما ❄️	
شب 🌙	
درون 🌀	
سکون 🛌	
پذیرنده 🤲	
نرم 🧖‍♀️	


🧘‍♀️ در بدن انسان:
اگر یین زیاد شود: احساس خستگی، سرما، افسردگی، بی‌حالی...


یین = زمین، سردی، پذیرش، آرامش

زمستان	یین ❄️	سرد، تاریک، ساکن
استراحت و خواب	یین 😴	آرامش، بازسازی
کلیه‌ها (ذخیره انرژی)	یین 🧊	خنک‌کننده، پایدار

      `,
      location:"",
      pressureAngle:"",
      pressureAmount:"",
      repetitions:"",
      time: "",
      extra:"",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "	یانگ (Yang)",
      Enname:"",
      faname:"",
      meridian:"",
      Fameridian:"",
      id:"",
      name:"",
      description:`
مذکر 🧘‍♂️
روشنایی ☀️
آسمان ☁️
گرما 🔥
روز 🌞
بیرون 🌪️
حرکت 🏃‍♂️
فعال 💪
سخت 🪨


🧘‍♀️ در بدن انسان:
اگر یانگ زیاد شود: بی‌خوابی، عصبانیت، گر گرفتگی، التهاب...

یانگ = خورشید، گرما، انرژی، فعالیت

تابستان	یانگ ☀️	گرم، روشن، فعال
ورزش شدید	یانگ 🏋️	حرکت، قدرت
قلب (فعال)	یانگ ❤️	تپش، حرکت خون

      `,
      location:"",
      pressureAngle:"",
      pressureAmount:"",
      repetitions:"",
      time: "",
      extra:"",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "",
      Enname:"",
      faname:"",
      meridian:"",
      Fameridian:"",
      id:"",
      name:"",
      description:"",
      location:"",
      pressureAngle:"",
      pressureAmount:"",
      repetitions:"",
      time: "",
      extra:"",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Hapgok, Hegu",
      faname:"هیگو",
      meridian:"Large Intestine Meridian (LI)",
      Fameridian:"مریدین روده بزرگ",
      id:"LI4",
      name:"LI4 Hegu هیگو",
      description:"روی دست",
      location:"محل نقطه: بین انگشت شصت و اشاره",
      pressureAngle:"زاویه فشار بصورت عمود",
      pressureAmount:"میزان فشار بین 7 تا 10",
      repetitions:"بین یک تا سه بار",
      time: "زمان بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یانگ",
      imageUrl:"assets/images/hegu.png",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    }, {
      category: "digestive",
      Enname:"Sinmun, Shenmen",
      faname:"شین مين",
      meridian:"Heart Meridian (HT)",
      Fameridian:"مریدین قلب",
      id:"HT7",
      name:"HT7 Shenmen شین مين",
      description:"روی دست",
      location:"محل نقطه: پایین انگشت کوچیکه بالاتر از مچ دست",
      pressureAngle:"زاویه فشار: فشار بصورت عمود",
      pressureAmount:"میزان فشار: بین 6 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Naegwan, Neiguan",
      faname:"نايگون",
      meridian:"Pericardium Meridian (PC)",
      Fameridian:"مریدین پریکارد (تامیانه قلب - یک لایه نازک و کیسه‌مانند است که قلب را در بر می‌گیرد)",
      id:"PC6",
      name:"PC6 Neiguan نايگون",
      description:"روی دست",
      location:"محل نقطه: روی دست دو سون بالاتر از مچ ",
      pressureAngle:"زاویه فشار: 45 رو به بالا",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یین",
      imageUrl:"",
      desc: "تهوع، اضطراب، مشکلات گوارشی، آرامش‌بخش بسیار قوی",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Gokji, Quchi",
      faname:"کوچی",
      meridian:"Large Intestine Meridian (LI)",
      Fameridian:"مریدین روده بزرگ",
      id:"LI11",
      name:"LI11 Quchi کوچی ",
      description:"روی دست",
      location:"محل نقطه: خط آرنج دست نیم سون پایینتر ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 2 به بالا",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یانگ",
      imageUrl:"یانگ",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Jigu, Zhigou",
      faname:"ژیگو",
      meridian:"Triple Energizer (TE / SJ)",
      Fameridian:"مریدین سه‌گانه یا سه‌گرم‌کننده",
      id:"TE6",
      name:"TE6 Zhigou ژیگو",
      description:"پشت دست",
      location:"محل نقطه: سه سون بالاتر از اول پشت دست ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 4 تا 7",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Daehoeng, Daheng",
      faname:"داهینگ",
      meridian:"Spleen Meridian (SP)",
      Fameridian:"مریدین طحال",
      id:"SP15",
      name:"SP15 Daheng داهینگ",
      description:"در امتداد ناف روی شکم",
      location:"محل نقطه: 4 سون یا چهار بند انگشت اطراف خط افقی ناف ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Gihae, Qihai",
      faname:"کی های",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV6",
      name:"CV6 Qihai کی های",
      description:"زیر ناف روی شکم",
      location:"محل نقطه: یک و نیم سون دو عرض انگشت زیر ناف ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Jungwan, Zhongwan",
      faname:"ژون گون",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV12",
      name:"CV12 Zhongguan ژون گون",
      description:"",
      location:"محل نقطه: ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra: "مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Yangmun, Liangmen",
      faname:"لانگ مین",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST21",
      name:"ST21 Liangmen لانگ مین",
      description:"روی شکم",
      location:"محل نقطه: دو سون از اطراف CV12",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Joksamni, Zusanli",
      faname:"ژوسان لی",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST36",
      name:"ST36 Zusanli ژوسان لی",
      description:"روی پا زیر زانو",
      location:"محل نقطه: زیر کشک زانو سمت بیرون زیر استخون گرده",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 6 تا 8",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Sameumgyo, Sanyinjiao",
      faname:"سانین جیو",
      meridian:"Spleen Meridian (SP)",
      Fameridian:"مریدین طحال",
      id:"SP6",
      name:"SP6 Sanyinjiao سانین جیو",
      description:"",
      location:"محل نقطه: داخل پا از مچ پا 4 عرض انگشت بالاتر از پشت استخوان فشار بیارید",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 7 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Sinmaek, Shenmai",
      faname:"شین مای",
      meridian:"Bladder Meridian (BL)",
      Fameridian:"مریدین مثانه",
      id:"BL62",
      name:"BL62 Shenmai شین مای",
      description:"",
      location:"محل نقطه: بیرون پا زیر قوزک  یکم به سمت جلو پا ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 5 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Guheo, Qiuxu",
      faname:"",
      meridian:"Gall Bladder Meridian (GB)",
      Fameridian:"مریدین کیسه صفرا",
      id:"GB40",
      name:"GB40 Qiuxu",
      description:"روی پا قسمت مچ",
      location:"محل نقطه: خط بین انگشت کوچیکه رو بگیر بیار تا مچ پا روی پا ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 5 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Taechung, Taichong",
      faname:"تایچونگ",
      meridian:"Liver Meridian (LR)",
      Fameridian:"مریدین کبد",
      id:"LR3",
      name:"LR3 Taichong تایچونگ",
      description:"روی پا قسمت برآمدگی",
      location:"محل نقطه: روی پا بین انگشت شصت و بغلی رو تا استخوان اتصالشون بیار بالا ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 5 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"Naejeong, Neiting",
      faname:"نایتینگ",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST44",
      name:"ST44 Neiting نایتینگ",
      description:"",
      location:"محل نقطه: بین انشگت دوم و سوم پا",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 6 تا 10",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"رئیسه - یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
    {
      category: "digestive",
      Enname:"",
      faname:"",
      meridian:"",
      Fameridian:"",
      id:"تکمیلی",
      name:"",
      description:`
بعد اتمام نقاط شکمی در ناف مقداری روغن سیاه دانه می ریزیم و محکم دور ناف را در مدت هفت تا هشت دقیقه در جهت ساعتگرد میچرخانیم فشار در ناحیه ساعت 3 تا ساعت 6 را بیشتر وارد میکنیم
      `,
      location:"",
      pressureAngle:"",
      pressureAmount:"",
      repetitions:"",
      time: "",
      extra:"",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"",
      faname:"",
      meridian:"",
      Fameridian:"",
      id:"تکمیلی",
      name:"",
      description:`
•	کلیه فشار ها در ناحیه شکمی بین 3 تا 6 می باشد و با زاویه مستقیم
•	اعداد فرد در ناحیه شکمی مهمتر می باشد
•	اگه نقاط خطوط مریدین را میگیرید. نقاط را از اعداد کوچکتر به بزرگتر به ترتیب بگیرید
•	در ناحیه شکمی ردیف CV-12 و نقاط افقی این خط مثل نقاط ST-21 خیلی مهم هستند
      `,
      location:"",
      pressureAngle:" ",
      pressureAmount:"",
      repetitions:"",
      time: "",
      extra:"اعداد فرد در ناحیه شکمی مهمتر می باشد",
      imageUrl:"اگه نقاط خطوط مریدین را میگیرید. نقاط را از اعداد کوچکتر به بزرگتر به ترتیب بگیرید",
      desc: "ر ناحیه شکمی ردیف CV12 و نقاط افقی این خط مثل نقاط ST21 خیلی مهم هستند",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Seongmun, Shimen",
      faname:"",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV5",
      name:"CV5 Shimen شیمین",
      description:"تکمیلی",
      location:"محل نقطه: دو سون زیر ناف یا دو بند انگشت زیر ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Gihae, Qihai",
      faname:"",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV6",
      name:"CV6 Qihai",
      description:"تکمیلی",
      location:"محل نقطه: یک و نیم سون زیر ناف یا عرض دو انگشت زیر ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"umgyo, Yinjiao",
      faname:"",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV7",
      name:"CV7 Yinjiao",
      description:"تکمیلی",
      location:"محل نقطه: یک سون زیر ناف یا یک بند انگشت زیر ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Singwol, Shenque",
      faname:"",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV8",
      name:"CV8 Shenque",
      description:"تکمیلی",
      location:"محل نقطه: خود ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Subun, Shuifen",
      faname:"",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV9",
      name:"CV9 Shuifen",
      description:"تکمیلی",
      location:"محل نقطه: یک سون بالای ناف یا یک بند انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Hawan, Xiawan",
      faname:"",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV10",
      name:"CV10 Xiawan",
      description:"تکمیلی",
      location:"محل نقطه: دو سون بالای ناف یا دو بند انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Geolli, Jianli",
      faname:"",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV11",
      name:"CV11 Jianli",
      description:"تکمیلی",
      location:"محل نقطه: سه سون بالای ناف یا عرض چهار انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Jungwan, Zhongwan",
      faname:"",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV12",
      name:"CV12 Zhongwan",
      description:"تکمیلی",
      location:"محل نقطه: چهار سون بالای ناف عرض چهار انگشت بعلاوه یک بند انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Sangwan, Shangwan",
      faname:"",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV13",
      name:"CV13 Shangwan",
      description:"تکمیلی",
      location:"محل نقطه: پنج سون بالا ناف یا عرض چهار انگشت بعلاوه دو بند انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Geogwol, Juque",
      faname:"",
      meridian:"Conception Vessel (CV / REN)",
      Fameridian:"مریدین محوری قدامی یا رِن",
      id:"CV14",
      name:"CV14 Juque",
      description:"تکمیلی",
      location:"محل نقطه: شش سون بالای ناف یا دوتا عرض چهار انگشت شخص بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"مسیر جلویی بدن، مرتبط با یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Saman, Siman",
      faname:"",
      meridian:"Kidney Meridian (KI)",
      Fameridian:"مریدین کلیه",
      id:"KI14",
      name:"KI14 Siman",
      description:"تکمیلی",
      location:"محل نقطه: نیم سون طرفین سی وی 5 - دو سون زیر ناف یا دو بند انگشت زیر ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Jungju, Zhongzhu",
      faname:"",
      meridian:"Kidney Meridian (KI)",
      Fameridian:"مریدین کلیه",
      id:"KI15",
      name:"KI15 Zhongzhu",
      description:"تکمیلی",
      location:"محل نقطه: نیم سون طرفین سی وی 7 - یک  سون زیر ناف یا یک بند انگشت زیر ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Hwangsu, Huangshu",
      faname:"",
      meridian:"Kidney Meridian (KI)",
      Fameridian:"مریدین کلیه",
      id:"KI16",
      name:"KI16 Huangshu",
      description:"تکمیلی",
      location:"محل نقطه: نیم سون طرفین ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Sanggok, Shangqu",
      faname:"",
      meridian:"Kidney Meridian (KI)",
      Fameridian:"مریدین کلیه",
      id:"KI17",
      name:"KI17 Shangqu",
      description:"تکمیلی",
      location:"محل نقطه: نیم سون طرفین سی وی 10 دو سون بالای ناف یا دو بند انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Seokgwan, Shiguan",
      faname:"",
      meridian:"Kidney Meridian (KI)",
      Fameridian:"مریدین کلیه",
      id:"KI18",
      name:"KI18 Shiguan",
      description:"تکمیلی",
      location:"محل نقطه:  نیم سون طرفین سی وی 11 سه سون بالای ناف یا عرض چهار انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Eumdo, Yindu",
      faname:"",
      meridian:"Kidney Meridian (KI)",
      Fameridian:"مریدین کلیه",
      id:"KI19",
      name:"KI19 Yindu",
      description:"تکمیلی",
      location:"محل نقطه: نیم سون طرفین سی وی 12  چهار سون بالای ناف عرض چهار انگشت بعلاوه یک بند انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Boktonggok, Futonggu",
      faname:"",
      meridian:"Kidney Meridian (KI)",
      Fameridian:"مریدین کلیه",
      id:"KI20",
      name:"KI20 Futonggu",
      description:"تکمیلی",
      location:"محل نقطه: نیم سون طرفین سی وی 13  پنج سون بالا ناف یا عرض چهار انگشت بعلاوه دو بند انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Yumun, Youmen",
      faname:"",
      meridian:"Kidney Meridian (KI)",
      Fameridian:"مریدین کلیه",
      id:"KI21",
      name:"KI21 Youmen",
      description:"تکمیلی",
      location:"محل نقطه: نیم سون طرفین سی وی 14 شش سون بالای ناف یا دوتا عرض چهار انگشت شخص بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یین",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Buryong, Burong",
      faname:"",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST19",
      name:"ST19 Burong",
      description:"",
      location:"محل نقطه: دو سون اطراف سی وی 14 شش سون بالای ناف یا دوتا عرض چهار انگشت شخص بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Seungman, Chengman",
      faname:"",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST20",
      name:"ST20 Chengman",
      description:"",
      location:"محل نقطه: دو سون اطراف سی وی 13  پنج سون بالا ناف یا عرض چهار انگشت بعلاوه دو بند انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Yangmun, Liangmen",
      faname:"",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST21",
      name:"ST21 Liangmen",
      description:"",
      location:"محل نقطه: دو سون اطراف سی وی 12  چهار سون بالای ناف عرض چهار انگشت بعلاوه یک بند انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Gwanmun, Guanmen",
      faname:"",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST22",
      name:"ST22 Guanmen",
      description:"",
      location:"محل نقطه: دو سون اطراف سی وی 11 سه سون بالای ناف یا عرض چهار انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Taeeul, Taiyi",
      faname:"",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST23",
      name:"ST23 Taiyi",
      description:"",
      location:"محل نقطه: دو سون اطراف سی وی 10 دو سون بالای ناف یا دو بند انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Hwaryungmun, Huaroumen",
      faname:"",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST24",
      name:"ST24 Huaroumen",
      description:"",
      location:"محل نقطه: دو سون اطراف سی وی 9 یک سون بالای ناف یا یک بند انگشت بالای ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Cheonchu, Tianshu",
      faname:"",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST25",
      name:"ST25 Tianshu",
      description:"",
      location:"محل نقطه: دو سون اطراف ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Oereung, Wailing",
      faname:"",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST26",
      name:"ST26 Wailing",
      description:"",
      location:"محل نقطه: دو سون اطراف سی وی 7 یک سون زیر ناف یا یک بند انگشت زیر ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "digestive",
      Enname:"Daegeo, Daju",
      faname:"",
      meridian:"Stomach Meridian (ST)",
      Fameridian:"مریدین معده",
      id:"ST27",
      name:"ST27 Daju",
      description:"",
      location:"محل نقطه: دو سون اطراف سی وی 5 دو سون زیر ناف یا دو بند انگشت زیر ناف",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"یانگ",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "1",
    },
    {
      category: "",
      Enname:"",
      faname:"",
      meridian:"",
      Fameridian:"",
      id:"",
      name:"",
      description:"",
      location:"محل نقطه: ",
      pressureAngle:"زاویه فشار: ",
      pressureAmount:"میزان فشار: بین 3 تا 6",
      repetitions:"تکرار: بین یک تا سه بار",
      time: "زمان: بین 30 ثانیه تا 3 دقیقه",
      extra:"",
      imageUrl:"",
      desc: "",
      descrip: "",
      descExtra: "",
      supplementary: "",
    },
  ];
    constructor() { }

  
    
    getAllNerves(): NervesModel[] {
      return this.nerves;
    }
    getAllShuffleNerves(): NervesModel[] {
      return this.shuffle(this.nerves);
    }
    //برای اینکه هر سری باز میشه نظرات متفاوت باشند جابجا باشند در نمایش
    private shuffle(array: NervesModel[]): NervesModel[] {
      const copy = [...array];
      for (let i = copy.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [copy[i], copy[j]] = [copy[j], copy[i]];
      }
      return copy;
    }
    searchNerves(term: string): NervesModel[] {
      const lowerTerm = term.toLowerCase();
      return this.nerves.filter(c =>
        c.name.toLowerCase().includes(lowerTerm) ||
        c.description.toLowerCase().includes(lowerTerm) ||
        c.location.toLowerCase().includes(lowerTerm) ||
        c.pressureAngle.toLowerCase().includes(lowerTerm) ||
        c.pressureAmount.toLowerCase().includes(lowerTerm) ||
        c.repetitions.toLowerCase().includes(lowerTerm) ||
        c.time.toLowerCase().includes(lowerTerm) ||
        c.extra.toLowerCase().includes(lowerTerm)
      );
    }
    searchNameNerves(term: string): NervesModel[] {
      const lowerTerm = term.toLowerCase();
      return this.nerves.filter(c =>
        c.name.toLowerCase().includes(lowerTerm)
      );
    }

  getAllByCategory(category: string): NervesModel[] {
    return this.nerves.filter(p => p.category === category);
  }

  /** سرچ در یک دسته */
  searchCategory(category: string, term: string): NervesModel[] {
    const lower = term.toLowerCase();
    return this.getAllByCategory(category).filter(p =>
      p.name.toLowerCase().includes(lower) ||
      p.location.toLowerCase().includes(lower) ||
      p.description.toLowerCase().includes(lower)
    );
  }

  
  /** سرچ در یک دسته */
  searchCategoryName(category: string, term: string): NervesModel[] {
    const lower = term.toLowerCase();
    return this.getAllByCategory(category).filter(p =>
      p.name.toLowerCase().includes(lower) 
    );
  }

  /** shuffle یک دسته */
  shuffleCategory(category: string): NervesModel[] {
    const arr = [...this.getAllByCategory(category)];
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }


}
